/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fsu.continuousintegration.project.gui;

import fsu.ContinuousIntegration.Project.DAL.CRUD.PersonData;
import fsu.ContinuousIntegration.Project.DAL.Entities.Person;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author fsureau
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listView = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setLayout(new java.awt.BorderLayout());

        listView.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listView);

        leftPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Charger les données");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onLoadDataMouseClick(evt);
            }
        });
        leftPanel.add(jButton1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(leftPanel, java.awt.BorderLayout.WEST);
        leftPanel.getAccessibleContext().setAccessibleName("");

        rightPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        rightPanel.setName(""); // NOI18N
        rightPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(rightPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onLoadDataMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onLoadDataMouseClick
        PersonData data = new PersonData();
        ArrayList<Person> results = data.getAll();

        DefaultListModel listModel = new DefaultListModel();
        for (Person person : results) {
            listModel.addElement(person.getFirstName() + " " + person.getLastName());
        }
        listView.setModel(listModel);
    }//GEN-LAST:event_onLoadDataMouseClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JList listView;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
